import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "500", "700"], // Include additional weights if needed
  style: ["normal", "italic"], // Add styles if required
  subsets: ["latin"],
});

export const metadata = {
  title: "Don Bosco Iringa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
